import random

# fruits = ["Apple", "Mango", "Orange", "Watermelon", "Papaya"]
#
# for fruit in fruits:
#     print(fruit)
#     print(f"I want to eat {fruit}")
#
# print(fruits)
# print(fruit)

#----------------------------------------------------------------------------------------------------

# students_scores = [110, 111, 135, 108, 141, 120, 107, 143, 142, 104, 118, 146, 106, 133, 113]
#
# max_score = 0
# for score in students_scores:
#     if score > max_score:
#         max_score = score
#
# print(max_score)

#-----------------------------------------------------------------------------------------------------
# sum = 0
# for number in range(1, 101):
#     sum += number
#
# print(sum)

#Simple and Easy Code
# alphabet_list = [
#     'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
#     'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'
# ]
# numbers_list = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
# symbols_list = ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '=', '+', '[', ']', '{', '}']
#
# print("Welcome to the password Generator!")
# ps_letter = int(input("How many letters you would like to have in your password? \n"))
# ps_symbol = int(input("How many symbols would you like in your password? \n"))
# ps_number = int(input("How many numbers would you like in your password? \n"))
#
# password = ""
# for char in range(0, ps_letter):
#     password += random.choice(alphabet_list)
#
# for char in range(0, ps_symbol):
#     password += random.choice(symbols_list)
#
# for char in range(0, ps_number):
#     password += random.choice(numbers_list)
#
# print(f"This is your password generated by this app: {password}")

#---------------------------------------------------------------------------------------------------

# import random
#
# # Define character lists
# alphabet_list = list("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz")
# numbers_list = list("0123456789")  # Now numbers are stored as strings
# symbols_list = list("!@#$%^&*()-_=+[]{}")
#
# print("Welcome to the password Generator!")
#
# # User input for password structure
# ps_letter = int(input("How many letters would you like to have in your password? \n"))
# ps_symbol = int(input("How many symbols would you like in your password? \n"))
# ps_number = int(input("How many numbers would you like in your password? \n"))
#
# # Generate random selections
# sec1 = random.sample(alphabet_list, ps_letter)
# sec2 = random.sample(symbols_list, ps_symbol)
# sec3 = random.sample(numbers_list, ps_number)  # Numbers are now strings
#
# # Combine all selected characters into a list
# sample_pass = sec1 + sec2 + sec3
#
# # Shuffle the list to randomize character order
# random.shuffle(sample_pass)
#
# # Convert list to a single string
# final_pass = "".join(sample_pass)
#
# print(f"\nThis is your generated password: {final_pass}")

# -------------------------------------------------------------------------------------------------
# Hard Level Code using for loop
#
# alphabet_list = [
#      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
#      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'
#  ]
# numbers_list = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
# symbols_list = ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '=', '+', '[', ']', '{', '}']
#
# ps_letter = int(input("How many letters would you like to have in your password? \n"))
# ps_symbol = int(input("How many symbols would you like in your password? \n"))
# ps_number = int(input("How many numbers would you like in your password? \n"))
#
# password_list = []
# for char in range(0, ps_letter):
#     password_list.append(random.choice(alphabet_list))
#
# for char in range(0, ps_symbol):
#     password_list.append(random.choice(symbols_list))
#
# for char in range(0, ps_number):
#     password_list.append(random.choice(numbers_list))
#
# print(password_list)
# random.shuffle(password_list)
# print(password_list)
#
# password = ""
# for char in password_list:
#     password += char
#
# print(f"Your final password is: {password}")

#---------------------------------------------------------------------------------------------------------------------------------------

alphabet_list = [
     'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
     'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'
 ]
numbers_list = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols_list = ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '=', '+', '[', ']', '{', '}']

ps_letter = int(input("How many letters would you like to have in your password? \n"))
ps_symbol = int(input("How many symbols would you like in your password? \n"))
ps_number = int(input("How many numbers would you like in your password? \n"))

password_list = []

for char in range(0, ps_letter):
    password_list.append(random.choice(alphabet_list))

for char in range(0, ps_symbol):
    password_list.append(random.choice(symbols_list))

for char in range(0, ps_number):
    password_list.append(random.choice(numbers_list))

print(password_list)
random.shuffle(password_list)
print(password_list)

password = ""

for char in password_list:
    password += char

print(f"Your password is: {password}")